### ISSUE TITLE
Passing gradient to FSMenuItem does not do anything

### ISSUE THREAD

**Issue by Ro-El** [yako-dev/flutter-full-screen-menu#4]
Hi,

FSMenuItem(
 icon: Icon(Icons.ac_unit, color: Colors.white),
 text: Text('On time'),
 onTap: () => print('On time'),
 gradient: **<< THIS DOES NOTHING**
),

Passing anything into gradient for FSMenuItem has no impact.
I'm fairly certain your FullScreenMenuBaseWidget uses the index of the FSMenuItem in the items list to pull a gradient from your gradients list. This should be the intended way for this to work except when FSMenuItem is intentionally passed a different gradient e.g. 
LinearGradient(colors: [
    Colors.pink,
    Colors.pink[300],
  ])

A fix for this is necessary for the user to be able to use custom colors for the menu items.

**Comment by yadaniyil** [comment]
Hi, fixed in v1.0.0
