### ISSUE TITLE
Pressing software back button on android will pop the scope of the page underneath the menu

### ISSUE THREAD

**Issue by Ro-El** [yako-dev/flutter-full-screen-menu#5]
Hi,

Assuming you don't implement willPopScope, pressing the back button on android while the full screen menu is open will close the app. Expectation is that, just like all bottomSheets, dialogs, etc. pressing the back button should hide the menu.

This can be solved by doing something like: 
onWillPop: () async {
        FullScreenMenu.isVisible ? FullScreenMenu.hide() : **<implement dialog to close app>**;
        return false;
      },

But that doesn't seem like the way this should work.

**Comment by yadaniyil** [comment]
Hi, thanks for the issue. Please check the example app in the 1.0.0 version of the plugin, it contains an example of WillPopScope usage to close the menu on the back button tap.
